name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Build
      shell: cmd
      run: "\"C:/Program Files (x86)/Inno Setup 6/ISCC.exe\" LI-Alternate-Installer.iss"
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        path: 
          "bin/LEGO Island Alternate Installer.exe"

    - name: Upload to Releases
      shell: bash
      if: github.event_name == 'push'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TRAVIS_REPO_SLUG: le717/Island-Alternate-Installer
        TRAVIS_COMMIT: ${{ github.sha }}
      run: |
        curl -fLOSs --retry 2 --retry-delay 60 https://raw.githubusercontent.com/probonopd/uploadtool/master/upload.sh
        ./upload.sh "bin/LEGO Island Alternate Installer.exe"
